stages:
  make_dataset:
    cmd: python3 src/data/make_dataset.py data/raw/train.csv data/interim/train.pkl
    deps:
    - data/raw/train.csv
    - src/data/make_dataset_.py
    outs:
    - data/interim/
