stages:
  make_dataset:
    cmd: python src/data/make_dataset.py data/raw/train.csv data/interim/train.pkl
      data/interim/target.pkl
    deps:
    - data/raw/train.csv
    - src/data/make_dataset.py
    outs:
    - data/interim/

  features:
    cmd: python src/features/build_features.py data/interim/train.pkl data/processed/train.pkl
    deps:
    - data/interim/target.pkl
    - data/interim/train.pkl
    - src/features/build_features.py
    outs:
    - data/processed

  train_models:
    cmd: python src/models/train_model.py data/processed/train.pkl data/interim/target.pkl models
    deps:
    - data/interim/target.pkl
    - data/processed/train.pkl
    - src/models/train_model.py
    outs:
    - models
